---
name: "JellyfinHeaderAuth"
guid: "df78a0dc-a52a-4a9b-bae4-3f60390b83c4"
version: "1.0.0.7"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Jellyfin plugin for header based authentication"
description: >
  This plugin authenticates users based on the 'X-Forwarded-UserName' header value.

category: "Authentication"
owner: "pikami"
artifacts:
  - "Jellyfin.Plugin.JellyfinHeaderAuth.dll"
changelog: >
  changelog
